G = {
    'Belém': [{'cidade': 'Salvador', 'tempo': 4, 'empresa': 'C', 'numero': 1992, 'bilhetes': 10, 'preco' : 350},
              {'cidade': 'Recife', 'tempo': 3, 'empresa': 'B', 'numero': 1993, 'bilhetes': 1,'preco' : 450},
              {'cidade': 'Goiás', 'tempo': 2, 'empresa': 'A', 'numero': 1993, 'bilhetes': 1, 'preco' : 268}],
    'São Paulo': [{'cidade': 'Belém', 'tempo': 5, 'empresa': 'B', 'numero': 1979, 'bilhetes': 10, 'preco' : 500},
                  {'cidade': 'Porto Alegre', 'tempo': 3,
                   'empresa': 'B', 'numero': 1004, 'bilhetes': 10, 'preco' : 310},
                  {'cidade': 'Rio de Janeiro', 'tempo': 1, 'empresa': 'C', 'numero': 1985, 'bilhetes': 10, 'preco' : 180}],

    'Porto Alegre': [{'cidade': 'Salvador', 'tempo': 3, 'empresa': 'A', 'numero': 1994, 'bilhetes': 10, 'preco' : 475},
                     {'cidade': 'Belém', 'tempo': 6, 'empresa': 'C',
                      'numero': 1995, 'bilhetes': 10, 'preco' : 525},
                     {'cidade': 'Goiás', 'tempo': 1, 'empresa': 'A', 'numero': 1996, 'bilhetes': 10, 'preco' : 298}],
    'Goiás': [{'cidade': 'Belém', 'tempo': 4, 'empresa': 'A', 'numero': 1997, 'bilhetes': 10, 'preco' : 180},
                 {'cidade': 'Porto Alegre', 'tempo': 3,
                  'empresa': 'B', 'numero': 1998, 'bilhetes': 10, 'preco' : 230},
                 {'cidade': 'Recife', 'tempo': 4, 'empresa': 'A', 'numero': 1974, 'bilhetes': 10, 'preco' : 440}],

    'Recife': [{'cidade': 'Salvador', 'tempo': 2, 'empresa': 'C', 'numero': 1999, 'bilhetes': 10, 'preco' : 200},
               {'cidade': 'Rio de Janeiro', 'tempo': 4, 'empresa': 'C', 'numero': 1980, 'bilhetes': 10, 'preco' : 370}],
    'Salvador': [{'cidade': 'Belém', 'tempo': 1, 'empresa': 'A', 'numero': 1990, 'bilhetes': 10, 'preco' : 350},
                 {'cidade': 'São Paulo', 'tempo': 2, 'empresa': 'B', 'numero': 1991, 'bilhetes': 10,'preco' : 280}],
    'Rio de Janeiro': [{'cidade': 'São Paulo', 'tempo': 1, 'empresa': 'C', 'numero': 1986, 'bilhetes': 10, 'preco' : 180},
                        {'cidade': 'Salvador', 'tempo': 3, 'empresa': 'B', 'numero': 1578, 'bilhetes': 10, 'preco' : 260},
                       {'cidade': 'Recife', 'tempo': 4, 'empresa': 'A', 'numero': 1578, 'bilhetes': 10, 'preco' : 375 }]}